version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./crudproject:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres

  db:
    image: postgres:13
    container_name: django-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
